### PR TITLE
Added correct params for commands, made a lot of comments.

### PR DESCRIPTION
**Pull request by Exxonnnnnn**
There's quite a few issues here.

- You use CDCommands but you have a handlers folder?
- You connect to Mongo even though CDCommands does this for you
- You close your connection to mongo
- You haven't added the correct params for commands, some params are required. (name, description, details, min, max, usage, noDisable, category, run
- You have done quite a lot of  `client.on` events, this is not how you do it using CDCommands
- You have made invalid event files
- You have made invalid feature files

What I have done:
- Made your eval command pog
- Added the correct command params
- Made comments in quite a lot of places.

What you should do:
- Read CDCommands README either on our [GitHub](https://github.com/CreativeDevelopments/CDCommands/blob/main/README.md) or on our [NPM Page](https://npmjs.com/package/cdcommands)
- Do `npm i sourcebin` (Used for your eval command)
- Take a JavaScript Course (Yes ik I need to as well kek), [CodeCademy has a good one](https://www.codecademy.com/learn/introduction-to-javascript)
- Try not to copy and paste if you don't know what is going on, after looking at it it seems like quite a lot has been copied from various places, if you don't know what it is doing then don't copy and paste. Learn and understand it first.
- For your reaction roles, you need to make two event files, one should contain the `messageReactionAdd` event and the other should contain the `messageReactionRemove` event. You can export the stuff you need from the command file and require it in the event file. You can see more about that [here](https://www.tutorialsteacher.com/nodejs/nodejs-module-exports) or [here](https://www.freecodecamp.org/news/node-module-exports-explained-with-javascript-export-function-examples/).
- I'll be making a CDCommands-Examples repository, once it's made I would highly recommend checking it out.
- If you need help using CDCommands, join our [Support Server](https://discord.gg/jUNbV5u)
- Update your message.json file to the latest one that works with the version of CDCommands you are using, you can find that [here, on our GitHub](https://github.com/CreativeDevelopments/CDCommands/blob/main/src/Base/message.json)
- Use CDCommands to it's full potential. You have a lot of if or if else statements checking to see if the author ID is your ID, literally just put devOnly: true, it will make your code shorter and cleaner.

I've kinda forgotten everything else I was gonna right here, but I've included most stuff.

### CODE REVIEW

**Comment by zytesas** [comment]
> There's quite a few issues here.
> 
> * You use CDCommands but you have a handlers folder?
> * You connect to Mongo even though CDCommands does this for you
> * You close your connection to mongo
> * You haven't added the correct params for commands, some params are required. (name, description, details, min, max, usage, noDisable, category, run
> * You have done quite a lot of  `client.on` events, this is not how you do it using CDCommands
> * You have made invalid event files
> * You have made invalid feature files
> 
> What I have done:
> 
> * Made your eval command pog
> * Added the correct command params
> * Made comments in quite a lot of places.
> 
> What you should do:
> 
> * Read CDCommands README either on our [GitHub](https://github.com/CreativeDevelopments/CDCommands/blob/main/README.md) or on our [NPM Page](https://npmjs.com/package/cdcommands)
> * Do `npm i sourcebin` (Used for your eval command)
> * Take a JavaScript Course (Yes ik I need to as well kek), [CodeCademy has a good one](https://www.codecademy.com/learn/introduction-to-javascript)
> * Try not to copy and paste if you don't know what is going on, after looking at it it seems like quite a lot has been copied from various places, if you don't know what it is doing then don't copy and paste. Learn and understand it first.
> * For your reaction roles, you need to make two event files, one should contain the `messageReactionAdd` event and the other should contain the `messageReactionRemove` event. You can export the stuff you need from the command file and require it in the event file. You can see more about that [here](https://www.tutorialsteacher.com/nodejs/nodejs-module-exports) or [here](https://www.freecodecamp.org/news/node-module-exports-explained-with-javascript-export-function-examples/).
> * I'll be making a CDCommands-Examples repository, once it's made I would highly recommend checking it out.
> * If you need help using CDCommands, join our [Support Server](https://discord.gg/jUNbV5u)
> * Update your message.json file to the latest one that works with the version of CDCommands you are using, you can find that [here, on our GitHub](https://github.com/CreativeDevelopments/CDCommands/blob/main/src/Base/message.json)
> * Use CDCommands to it's full potential. You have a lot of if or if else statements checking to see if the author ID is your ID, literally just put devOnly: true, it will make your code shorter and cleaner.
> 
> I've kinda forgotten everything else I was gonna right here, but I've included most stuff.

Oh holy shit, I never would have anticipated someone actually looking through all this hot garbage.

This entire "project" started from reading through the discord.js documentation.  There is a LOT of arbitrary old code that I have neglected to clean up, as I am obviously in the process of learning.  The "handlers" folder was something that had become deprecated after I'd taken the plunge to incorporate CDCommands into it.  I only recently pushed the commits of the incorporation to the main branch, so I'm interested to see what I've neglected for things that I *thought I understood*.  

I'm actually in the process of running through CodeCademy's JS class right now.  I actually am a huge advocate of not using things that you don't understand, so I tried to at the very least type it out instead of "copy pasting" it, and follow along with what is doing what (hence why there are probably errors/things missing).

Some of the issues you've stated are just deprecated things that just need to be refactored/removed/cleaned up.  So I'll have to finally decide to clean it up a little.  Reactionroles, other old commands/events/features, even the connection to mongodb (which I don't call anywhere in the entire project... yet).  S'all my road leading to the mess that it is now. :P

Like I stated previously, I never thought it would be looked at, but I want to seriously thank you for taking the time to painfully look through everything.  That's actually super awesome.

**Comment by zytesas** [comment]
Oh and I am in the CDCommands discord, (as well as the WOK/Aeroware discords).  I don't talk much, I just try to read and find little tidbits to learn from.

**Review by zytesas — APPROVED** [review]
Actually super awesome that this happened, I'm going to look through your suggestions and put more focus into learning from resources rather than work things out.

**Comment by Exxonnnnnn** [comment]
No worries, if you need anything else ask in the WOK GitHub or our one. Someone will be able to help there.

**Pull request merged**
